
services:
  ex_forecastio.app_configuration:
      class: Keboola\ForecastIoExtractorBundle\Extractor\AppConfiguration
      arguments: [%app_name%, %ex_forecastio%]
  ex_forecastio.shared_storage:
      class: Keboola\ForecastIoExtractorBundle\Extractor\SharedStorage
      arguments: [@doctrine]
  ex_forecastio.job_executor:
      class: Keboola\ForecastIoExtractorBundle\Extractor\Executor
      arguments: [@ex_forecastio.app_configuration, @ex_forecastio.shared_storage, @syrup.temp]