sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build tests-with-report

script:
  - docker-compose run --rm tests-with-report

after_success:
  - docker images

deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true
