version: "2"

services:

  app:
    build: .
    image: keboola/forecastio-augmentation
    tty: true
    stdin_open: true
    command: ./tests.sh
    environment:
      - FORECASTIO_KEY

  dev:
    image: keboola/forecastio-augmentation
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - .:/code
    environment:
      - FORECASTIO_KEY