version: "2"

services:

  app:
    build: .
    image: keboola/forecastio-augmentation
    tty: true
    stdin_open: true
    command: ./tests.sh
    environment:
      - FORECASTIO_KEY
      - CODECLIMATE_REPO_TOKEN

  dev:
    image: keboola/forecastio-augmentation
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - .:/code
    environment:
      - FORECASTIO_KEY
      - CODECLIMATE_REPO_TOKEN

  tests-with-report:
    extends:
      service: app
    volumes:
      - ./.git:/code/.git
    command: sh -c './tests.sh && ./vendor/bin/test-reporter'